# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

TEAMID = ENV["TEAMID"]
GH_PAT = ENV["GH_PAT"]
GITHUB_WORKSPACE = ENV["GITHUB_WORKSPACE"]
GITHUB_REPOSITORY_OWNER = ENV["GITHUB_REPOSITORY_OWNER"]
FASTLANE_KEY_ID = ENV["FASTLANE_KEY_ID"]
FASTLANE_ISSUER_ID = ENV["FASTLANE_ISSUER_ID"]
FASTLANE_KEY = ENV["FASTLANE_KEY"]
DEVICE_NAME = ENV["DEVICE_NAME"]
DEVICE_ID = ENV["DEVICE_ID"]
ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"

platform :ios do
  desc "Build Caregiver"
  lane :caregiver_build do
    setup_ci if ENV['CI']
    
    update_project_team(
      path: "#{GITHUB_WORKSPACE}/LoopCaregiver/LoopCaregiver.xcodeproj",
      teamid: "#{TEAMID}"
    )

    api_key = app_store_connect_api_key(
      key_id: "#{FASTLANE_KEY_ID}",
      issuer_id: "#{FASTLANE_ISSUER_ID}",
      key_content: "#{FASTLANE_KEY}"
    )

    previous_build_number = latest_testflight_build_number(
      app_identifier: "com.#{TEAMID}.loopkit.LoopCaregiver",
      api_key: api_key,
    )

    current_build_number = previous_build_number + 1

    increment_build_number(
      xcodeproj: "#{GITHUB_WORKSPACE}/LoopCaregiver/LoopCaregiver.xcodeproj",
      build_number: current_build_number
    )      
    
    match(
      type: "appstore",
      git_basic_authorization: Base64.strict_encode64("#{GITHUB_REPOSITORY_OWNER}:#{GH_PAT}"),
      app_identifier: [
        "com.#{TEAMID}.loopkit.LoopCaregiver",
        "com.#{TEAMID}.loopkit.LoopCaregiver.IntentExtension",
        "com.#{TEAMID}.loopkit.LoopCaregiver.WidgetExtension",
        "com.#{TEAMID}.loopkit.LoopCaregiver.watchkitapp",
        "com.#{TEAMID}.loopkit.LoopCaregiver.watchkitapp.WidgetExtension",
      ]
    )

    previous_build_number = latest_testflight_build_number(
      app_identifier: "com.#{TEAMID}.loopkit.LoopCaregiver",
      api_key: api_key,
    )

    current_build_number = previous_build_number + 1

    increment_build_number(
      xcodeproj: "#{GITHUB_WORKSPACE}/LoopCaregiver/LoopCaregiver.xcodeproj",
      build_number: current_build_number
    )
    
    mapping = Actions.lane_context[
      SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING
    ]

    update_code_signing_settings(
      path: "#{GITHUB_WORKSPACE}/LoopCaregiver/LoopCaregiver.xcodeproj",
      profile_name: mapping["com.#{TEAMID}.loopkit.LoopCaregiver"],
      code_sign_identity: "iPhone Distribution",
      targets: ["LoopCaregiver"]
    )

    update_code_signing_settings(
      path: "#{GITHUB_WORKSPACE}/LoopCaregiver/LoopCaregiver.xcodeproj",
      profile_name: mapping["com.#{TEAMID}.loopkit.LoopCaregiver.IntentExtension"],
      code_sign_identity: "iPhone Distribution",
      targets: ["LoopCaregiverIntentExtension"]
    )

    update_code_signing_settings(
      path: "#{GITHUB_WORKSPACE}/LoopCaregiver/LoopCaregiver.xcodeproj",
      profile_name: mapping["com.#{TEAMID}.loopkit.LoopCaregiver.WidgetExtension"],
      code_sign_identity: "iPhone Distribution",
      targets: ["LoopCaregiverWidgetExtension"]
    )

    update_code_signing_settings(
      path: "#{GITHUB_WORKSPACE}/LoopCaregiver/LoopCaregiver.xcodeproj",
      profile_name: mapping["com.#{TEAMID}.loopkit.LoopCaregiver.watchkitapp"],
      code_sign_identity: "iPhone Distribution",
      targets: ["LoopCaregiverWatchApp"]
    )

    update_code_signing_settings(
      path: "#{GITHUB_WORKSPACE}/LoopCaregiver/LoopCaregiver.xcodeproj",
      profile_name: mapping["com.#{TEAMID}.loopkit.LoopCaregiver.watchkitapp.WidgetExtension"],
      code_sign_identity: "iPhone Distribution",
      targets: ["LoopCaregiverWatchAppExtension"]
    )

    gym(
      export_method: "app-store",
      scheme: "LoopCaregiver",
      output_name: "LoopCaregiver.ipa",
      configuration: "Release",
      destination: 'generic/platform=iOS',
      buildlog_path: 'buildlog'
    )

    copy_artifacts(
      target_path: "artifacts",
      artifacts: ["*.mobileprovision", "*.ipa", "*.dSYM.zip"]
    )
  end

  desc "Push Caregiver to TestFlight"
  lane :caregiver_release do
    api_key = app_store_connect_api_key(
      key_id: "#{FASTLANE_KEY_ID}",
      issuer_id: "#{FASTLANE_ISSUER_ID}",
      key_content: "#{FASTLANE_KEY}"
    )
    
    upload_to_testflight(
      api_key: api_key,
      skip_submission: false,
      ipa: "LoopCaregiver.ipa",
      skip_waiting_for_build_processing: true,
    )
  end

  desc "Provision Caregiver Identifier"
  lane :caregiver_identifier do
    setup_ci if ENV['CI']
    ENV["MATCH_READONLY"] = false.to_s

    app_store_connect_api_key(
      key_id: "#{FASTLANE_KEY_ID}",
      issuer_id: "#{FASTLANE_ISSUER_ID}",
      key_content: "#{FASTLANE_KEY}"
    )

    def configure_bundle_id(name, identifier, capabilities)
      bundle_id = Spaceship::ConnectAPI::BundleId.find(identifier) || Spaceship::ConnectAPI::BundleId.create(name: name, identifier: identifier)
      capabilities.each { |capability|
        bundle_id.create_capability(capability)
      }
    end

    configure_bundle_id("LoopCaregiver", "com.#{TEAMID}.loopkit.LoopCaregiver", [
      Spaceship::ConnectAPI::BundleIdCapability::Type::APP_GROUPS,
    ])

    configure_bundle_id("LoopCaregiverIntentExtension", "com.#{TEAMID}.loopkit.LoopCaregiver.IntentExtension", [
      Spaceship::ConnectAPI::BundleIdCapability::Type::APP_GROUPS
    ])

    configure_bundle_id("LoopCaregiverWidgetExtension", "com.#{TEAMID}.loopkit.LoopCaregiver.WidgetExtension", [
      Spaceship::ConnectAPI::BundleIdCapability::Type::APP_GROUPS
    ])

    configure_bundle_id("LoopCaregiverWatch", "com.#{TEAMID}.loopkit.LoopCaregiver.watchkitapp", [
      Spaceship::ConnectAPI::BundleIdCapability::Type::APP_GROUPS
    ])

    configure_bundle_id("LoopCaregiverWatchWidgetExtension", "com.#{TEAMID}.loopkit.LoopCaregiver.watchkitapp.WidgetExtension", [
      Spaceship::ConnectAPI::BundleIdCapability::Type::APP_GROUPS
    ])

  end
  
  class CaregiverBuildError < StandardError; end
  
  def createCaregiverError(error_message)
      return CaregiverBuildError.new("Error: #{error_message}")
  end

  class CaregiverBuildError < StandardError; end

  def createCaregiverError(error_message)
      return CaregiverBuildError.new("Error: #{error_message}")
  end

  desc "Provision Caregiver Certificate"
  lane :caregiver_cert do
    setup_ci if ENV['CI']
    ENV["MATCH_READONLY"] = false.to_s
    
    app_store_connect_api_key(
      key_id: "#{FASTLANE_KEY_ID}",
      issuer_id: "#{FASTLANE_ISSUER_ID}",
      key_content: "#{FASTLANE_KEY}"
    )

    def validate_bundle_id(identifier)

      bundle_id = Spaceship::ConnectAPI::BundleId.find(identifier)

      # Throw an error if the bundle_id can't be found
      raise createCaregiverError("App Identifier not found for: #{identifier}") if bundle_id.nil?

      capabilities = bundle_id.get_capabilities

      # Try to find a capability where capability_type is "APP_GROUPS"
      app_group_capability_exists = false
      capabilities.each do |capability|
        if capability.capability_type == "APP_GROUPS"
          app_group_capability_exists = true
          break
        end
      end

      # Throw an error if no such capability exists
      raise createCaregiverError("APP_GROUPS capability not found for identifier: #{identifier}") unless app_group_capability_exists
    end

    #validate_bundle_id("com.#{TEAMID}.loopkit.LoopCaregiver")
    #validate_bundle_id("com.#{TEAMID}.loopkit.LoopCaregiver.IntentExtension")
    #validate_bundle_id("com.#{TEAMID}.loopkit.LoopCaregiver.WidgetExtension")
    #validate_bundle_id("com.#{TEAMID}.loopkit.LoopCaregiver.watchkitapp")
    #validate_bundle_id("com.#{TEAMID}.loopkit.LoopCaregiver.watchkitapp.WidgetExtension")
    
    match(
      type: "appstore",
      force: true,
      git_basic_authorization: Base64.strict_encode64("#{GITHUB_REPOSITORY_OWNER}:#{GH_PAT}"),
      app_identifier: [
        "com.#{TEAMID}.loopkit.LoopCaregiver",
        "com.#{TEAMID}.loopkit.LoopCaregiver.IntentExtension",
        "com.#{TEAMID}.loopkit.LoopCaregiver.WidgetExtension",
        "com.#{TEAMID}.loopkit.LoopCaregiver.watchkitapp",
        "com.#{TEAMID}.loopkit.LoopCaregiver.watchkitapp.WidgetExtension",
      ]
    )
  end

  desc "Validate Secrets"
  lane :validate_secrets do
    setup_ci if ENV['CI']
    ENV["MATCH_READONLY"] = true.to_s
    
    app_store_connect_api_key(
      key_id: "#{FASTLANE_KEY_ID}",
      issuer_id: "#{FASTLANE_ISSUER_ID}",
      key_content: "#{FASTLANE_KEY}"
    )
    
    def find_bundle_id(identifier)
      bundle_id = Spaceship::ConnectAPI::BundleId.find(identifier)
    end

    find_bundle_id("com.#{TEAMID}.loopkit.LoopCaregiver")

    match(
      type: "appstore",
      git_basic_authorization: Base64.strict_encode64("#{GITHUB_REPOSITORY_OWNER}:#{GH_PAT}"),
      app_identifier: [],
    )

  end

  desc "Nuke Certs"
  lane :nuke_certs do
    setup_ci if ENV['CI']
    ENV["MATCH_READONLY"] = false.to_s
    
    app_store_connect_api_key(
      key_id: "#{FASTLANE_KEY_ID}",
      issuer_id: "#{FASTLANE_ISSUER_ID}",
      key_content: "#{FASTLANE_KEY}"
    )
    
    match_nuke(
      type: "appstore",
      team_id: "#{TEAMID}",
      skip_confirmation: true,
      git_basic_authorization: Base64.strict_encode64("#{GITHUB_REPOSITORY_OWNER}:#{GH_PAT}")
    )
  end
end
